Use insertafter instead of insertbefore because of ansible bug
- If the file already exists with the exact entry it fails with error message:

...
IndexError: list index out of range